function Aboutus(){
    return(
        <div >
            <h1 >About us</h1>
            <p className="">KANYAMANI FASHIONS IS A WOMEN'S BOUTIQUE AND FABRIC STORE. WE ARE SPECIALIZED IN CREATING WOMEN'S DESIGNER WARE, DESIGNER BLOUSE, KIDS DESIGNER WARE, SAREE KUCHU, SAREE TASSEL, MAGGAM WORK, AARI WORK, COMPUTERIZED EMBROIDERY. WE SELL FABRICS LIKE COTTON, SILK, CREPE, GEORGETTE, LINEN, ORGANZA, POLYESTER, SATIN, RAYON, BROCADE AND MORE. WE ALSO SELL DESIGNER SAREES, PATTU SAREES, PARTY WARE SAREES, DAILY WARE SAREES, LADIES DRESS MATERIALS, LEGGINGS . COTTON THREADS, SILK THREADS, EMBROIDERY THREADS, ZARI THREADS, LACE, DORI, LEHANGA HANGINGS, TAILORING AND MAGGAM MATERIALS</p>
        </div>
        )
}
export default Aboutus;